name: test_sftp_modules

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: "**"

concurrency:
  group: ${{ github.repository }}-test_sftp_modules
  cancel-in-progress: false
  
jobs:
  security_check:
    runs-on: ubuntu-latest
    steps:
    - name: Get User Permission
      id: checkAccess
      uses: actions-cool/check-user-permission@v2
      with:
        require: write
        username: ${{ github.triggering_actor }}
    - name: Check User Permission
      if: steps.checkAccess.outputs.require-result == 'false'
      run: |
        echo "${{ github.triggering_actor }} does not have permissions on this repo."
        echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
        echo "Job originally triggered by ${{ github.actor }}"
        exit 1

  test_download:
    runs-on: ubuntu-latest
    needs: security_check
    if: github.repository_owner == 'BU-ISCIII'
    strategy:
      max-parallel: 1
      matrix:
        download_options: ["download_only", "download_clean", "delete_only"]
        target_folders: ["", "-t COD-test-1"]
      
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
      
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
      
    - name: Install package and dependencies
      run: |
        pip install -r requirements.txt
        pip install .
      
    - name: Run sftp_handle tests
      run: |
        python3 tests/test_sftp_modules.py --download_option ${{ matrix.download_options }} ${{ matrix.target_folders }}
      env:
        TEST_USER: ${{ secrets.TEST_USER }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_PORT: ${{ secrets.TEST_PORT }}
        OUTPUT_LOCATION: ${{ github.workspace }}/tests/

  test_wrapper:
    runs-on: ubuntu-latest
    needs: test_download
    if: github.repository_owner == 'BU-ISCIII'
    strategy:
      max-parallel: 1
      matrix:
        download_options: ["download_only", "download_clean"]
      
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
      
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
      
    - name: Install package and dependencies
      run: |
        pip install -r requirements.txt
        pip install .
                              
    - name: Run Wrapper tests
      run: |
        python3 tests/test_wrapper_handle.py --download_option ${{ matrix.download_options }}
      env:
        TEST_USER: ${{ secrets.TEST_USER }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_PORT: ${{ secrets.TEST_PORT }}
        OUTPUT_LOCATION: ${{ github.workspace }}/tests/